### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by N3XT14** [maxeth/react-type-animation#1]
pm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0 || ^17.0.0" from react-type-animation@1.1.2

Doesn't work with react 18 and henceforth will break for future versions

**Comment by maxeth** [comment]
> pm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: client@0.1.0 npm ERR! Found: react@18.1.0 npm ERR! node_modules/react npm ERR! react@"^18.0.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer react@"^15.0.0 || ^16.0.0 || ^17.0.0" from react-type-animation@1.1.2
> 
> Doesn't work with react 18 and henceforth will break for future versions

Sorry, I updated the dependencies to ```>= 15.0.0```, should work now.
