### ISSUE TITLE
Random Error with FIles

### ISSUE THREAD

**Issue by Arinji2** [maxeth/react-type-animation#11]
Hey so I was using the module which i installed from Npm. The module works fabulous with no bugs.. but there is always 3 errors which keep spamming my terminal on saving. Is there any fix for this since I like to keep my terminal clean from Errors.
Version:     "react-type-animation": "^2.1.1",

Compiled with warnings.

Failed to parse source map from 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\components\TypeAnimation\index.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\components\TypeAnimation\index.tsx'

Failed to parse source map from 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\hooks\useEffectOnce.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\hooks\useEffectOnce.tsx'

Failed to parse source map from 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\typical.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\typical.ts'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/react-type-animation/dist/esm/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\components\TypeAnimation\index.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\components\TypeAnimation\index.tsx'

WARNING in ./node_modules/react-type-animation/dist/esm/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\hooks\useEffectOnce.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\hooks\useEffectOnce.tsx'

WARNING in ./node_modules/react-type-animation/dist/esm/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\typical.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Arinjay\React Apps\articlechatbot\node_modules\react-type-animation\src\typical.ts'

webpack compiled with 3 warnings

**Comment by maxeth** [comment]
Hey,

check out this issue: https://github.com/maxeth/react-type-animation/issues/7 and specifically https://github.com/maxeth/react-type-animation/issues/7#issuecomment-1221507186 for a quick fix.

I assume you're also using create-react-app as I don't get any warnings when using Next.js. The source maps in the build output of the package look fine to me, so I unfortunately have no idea how to fix these warnings for now.
