### ISSUE TITLE
Line Breaks

### ISSUE THREAD

**Issue by Filimoa** [maxeth/react-type-animation#18]
Thanks for you work on this. I'm not sure if this is a duplicate of #12 but is there any way of adding line breaks? I'm working on rendering a paragraph and using `<br/>` or `\n` does not work. Thanks.

**Comment by Toriqul-Leon** [comment]
Same issue! Did you find the solution?

**Comment by maxeth** [comment]
I think you could get it working with the white-space css prop:

```js
<TypeAnimation
            style={{ whiteSpace: 'pre-line' }} 
            sequence={[
              `Line one
               Line Two\nLine Three
               Line Four\nLineFive
              `,
            ]}
            repeat={Infinity}
          />
```

Is this what you've been looking for?

**Comment by Toriqul-Leon** [comment]
> I think you could get it working with the white-space css prop:
> 
> ```js
> <TypeAnimation
>             style={{ whiteSpace: 'pre-line' }} 
>             sequence={[
>               `Line one
>                Line Two\nLine Three
>                Line Four\n LineFive
>               `
>             ]}
> 
>           />
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> Is this what you've been looking for?

This works for me! Thanks a lot mate. ❤️
