### ISSUE TITLE
Typing Animation Wrong in Firefox

### ISSUE THREAD

**Issue by routsabyasachi1** [maxeth/react-type-animation#2]
1st iteration in chrome
![image](https://user-images.githubusercontent.com/72302235/171985061-f189602c-23b4-49bb-9cd6-99ee7b009c4f.png)
1st iteration in firefox
![image](https://user-images.githubusercontent.com/72302235/171985103-1a933460-8193-46e0-88d4-5bd412475cd9.png)

and here is the code

<Typing speed={100} loop={true}><Typing.Reset count={1} delay={500} /><span>Shopping</span><Typing.Delay ms={1000} /><Typing.Backspace count={20} /></Typing>

**Comment by maxeth** [comment]
The code sample you provided is not valid syntax for this package, I'm sure you confused this package (which is ``react-type-animation``) with [react-typing-animation](https://github.com/notadamking/react-typing-animation). 

I suggest creating an issue there.
