### ISSUE TITLE
Have initial text ready

### ISSUE THREAD

**Issue by kevinlu1248** [maxeth/react-type-animation#20]
Hello,

Awesome package btw. I was wondering if there's a way of having initial text there, instead of initially having nothing and typing it out the first time.

**Comment by maxeth** [comment]
Hi, since the default wrapper for the animation is a `<span>`, you could just do something like this:  

```tsx
<span style={{ fontSize: '2em' }}>
      <span>We produce food for</span>{' '} // <--- will be pre-typed
      <RawTypeAnimation
        sequence={[
          'Mice',
          1000,
          'Hamsters',
          1000,
          'Pigs',
          1000,
          'Chinchillas',
          1000,
        ]}
        repeat={Infinity}
      />
    </span>
```
But in that case, you couldn't animate that pre-typed string later in the animation sequence.

**Comment by kevinlu1248** [comment]
Oh I meant like it is "We produce food for Mice" initially and "Mice" gets replaced by "Hamsters", etc.

**Comment by maxeth** [comment]
I see, so something like 

```tsx
    <TypeAnimation
       preRenderFirstString={true}
        sequence={[
          'A'
          1000,
          'B',
          1000,
          'C',
          1000
        ]}
        repeat={Infinity}
      />
```

Results in: 'A' (pre-rendered), 1s delay, 'B', 1s delay, 'C', 1s delay, 'A', ...

Sounds like a good feature, especially for SEO if you use server-side rendering.

**Comment by asp3** [comment]
hey! checking in on the `preRenderedFirstString` prop @maxeth

**Comment by maxeth** [comment]
> hey! checking in on the `preRenderedFirstString` prop @maxeth

Added https://react-type-animation.netlify.app/examples#initially-pre-rendered
