### ISSUE TITLE
Pause after deletion and before next string?

### ISSUE THREAD

**Issue by Toshinaki** [maxeth/react-type-animation#21]
Currently after one string is deleted, and the next string got typed immediately.

Any way to pause for a given seconds before typing next string?

**Comment by maxeth** [comment]
You can put any number inside the sequence which represents the amount of milliseconds to be awaited before typing the next string, so you could do something like this if I understand correctly:

```
  sequence={[
        'One', 
        1000, 
        '', // I think this is what you're looking for
        1000,
        'Two', 
      ]}
```

**Comment by Toshinaki** [comment]
OK, it worked.

Thank you!
