### ISSUE TITLE
Property 'sequence' does not exist on type 'IntrinsicAttributes & TypingProps'.

### ISSUE THREAD

**Issue by SMKH-PRO** [maxeth/react-type-animation#3]
Hi, 
using with NextJS, Typescript, but getting this error in VS CODE:
```
Type '{ cursor: true; sequence: (string | number)[]; wrapper: string; repeat: number; }' is not assignable to type 'IntrinsicAttributes & TypingProps'.
  Property 'sequence' does not exist on type 'IntrinsicAttributes & TypingProps'.

```
However, the project is working and rendered fine on the front but it's just showing me this error on VS Code.

<img src="https://i.ibb.co/bRV64ZK/Screenshot-2022-06-13-at-5-07-42-PM.png" alt="Screenshot-2022-06-13-at-5-07-42-PM" border="0">

<img src="https://i.ibb.co/m9ys8Hs/Screenshot-2022-06-13-at-5-16-52-PM.png" alt="Screenshot-2022-06-13-at-5-16-52-PM" border="0">

Packages:
    "react-type-animation": "^1.1.3"

DevDep:
    "@types/react-type-animation": "^1.1.0",

**Comment by maxeth** [comment]
Type declarations are included since version ```2.0.0``` by default now.
