### ISSUE TITLE
I want to stop the text generating animation at the middle of the content like ChatGPT

### ISSUE THREAD

**Issue by kananimaulik26** [maxeth/react-type-animation#31]
Is it possible to provide one button like "Stop generating", and when the user will click on this button then text-generating animation will stop
If there is no such kind of functionality in this package, then any idea how we can do this?
It will really helpful to me, apart from that this package is good for text animation
Thanks

**Comment by maxeth** [comment]
You will have to conditionally render the component using react state

```tsx
someState ? <TypeAnimation/> : <span>{currentlyTypedOutText}</span>
```

where currentlyTypedOutText is the content of the dom element.

To get that content you need pass a ref first
```tsx
const ref = React.createRef<HTMLSpanElement>(); 

<TypeAnimation ref={ref} {...} />
```

and then do something like this I think 

```tsx
ref.current.innerText
```


---

You'll have to play around with it, but this is not a package-specific feature, it's just traditional javascript/react.
