### ISSUE TITLE
Using inside text input/textarea

### ISSUE THREAD

**Issue by hjf** [maxeth/react-type-animation#32]
I'd like to use this as the placeholder of a textarea. Obviously it'd need to be text only, and not a whole component.

Maybe it can be split into a hook, so the text can be used as the placeholder prop in a Textarea element?

**Comment by maxeth** [comment]
Hey,

the package currently natively modifies DOM elements without actual React state, but we could also export the type function as a standalone hook without a component.

For now, you could just render a dummy `TypeAnimation` component with `style={{display:"none"}}`,  pass a `ref` to the `TypeAnimation` component and use something like [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to listen for any DOM changes of that element. Upon changes, you would grab its content via `ref.current.textContent` and set it in some state value, getting the most up-to-date text written by the component.

---

Or simplified without MutationObserver:

```tsx
export function CallbackExample() {
  const [tick, setTick] = useState(0);

// narrow down this component as much as possible — eg mage it just a wrapper for a TypeAnimation component — 
// so these re-renders dont cause performance issues
  useEffect(() => {
    const t = setTimeout(() => {
      setTick((p) => p + 1);
    }, 10);

    return () => clearInterval(t);
  }, [tick]);

  const [refNode, setRefNode] =
    useState<MutableRefObject<HTMLSpanElement>['current']>();

  const refCallback = useCallback(
    (nodeContent: MutableRefObject<HTMLSpanElement>['current']) => {
      console.log(nodeContent);
      setRefNode(nodeContent);
    },
    []
  );

  return (
    <>
      {refNode && <div>{refNode.textContent}</div>}

        <TypeAnimation
         style={{display:"none"}}
          ref={refCallback}
          sequence={["a", "b", "c"]}
        />

    </>
  );
}
```
