### ISSUE TITLE
Feature Request: Parameter to Remove Text Deletion

### ISSUE THREAD

**Issue by justin-slattery** [maxeth/react-type-animation#33]
Basically as the title says. As with other type-animation libraries, I am not sure why the default is to delete the text automatically, or at the very least, why there is no option to turn the deletion option off altogether. When first viewing the documentation, I had hoped that omitDeletionAnimation prevented the deletion from taking place, not simply removed the animation of the deletion. Adding in a parameter to prevent text deletion altogether would be very much appreciated.

**Comment by findubk** [comment]
is it fixed?
