### ISSUE TITLE
How to pass props to the wrapper element?

### ISSUE THREAD

**Issue by ankitjangir01** [maxeth/react-type-animation#38]

**Comment by maxeth** [comment]
What's your use case if I may ask? Which props do you need to pass to a native HTML element?

**Comment by ankitjangir01** [comment]
@maxeth 
I want to apply CSS to the text as `background-image: linear-gradient(...)`. Since I'm working with ReactJS, I wanted to pass the `style` prop. Even if I try to apply style using plain CSS, I need to name the text with some `class` or `id` which again doesn't seem to be supported here. Is there any alternative to this?

**Comment by salesp07** [comment]
Agreed, this would be a nice functionality to add, since styling is limited to the typing component's container as of now.

**Comment by maxeth** [comment]
@ankitjangir01 

Passing a custom `className` or `styles` – which gets applied to the wrapper element of the text – is supported. I'm not quite sure what change you're proposing. 

Take a look at the [source](https://github.com/maxeth/react-type-animation/blob/master/src/components/TypeAnimation/index.tsx#L107).
