### ISSUE TITLE
Add duration

### ISSUE THREAD

**Issue by harrisonhoward** [maxeth/react-type-animation#4]
Unsure if this is able to be done but the ability to change the duration of the animation would be great.

**Comment by maxeth** [comment]
Hey, I published a new version with types and a new ```speed``` prop that ranges from 0-100 (65 is the default "old" value) which determines how fast the animation is.

Is that what you meant with 'duration'?

You can install the new one and just change the import to ```import {TypeAnimation} from "react-type-animation" ```, there are no other breaking changes.

**Comment by harrisonhoward** [comment]
This is what I was looking for
