### ISSUE TITLE
SSR: useRef only works in Client Components

### ISSUE THREAD

**Issue by sstackus** [maxeth/react-type-animation#40]
Hey,

This doesn't seem to be working with SSR in Next.js v13.

```
Error: useRef only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/react-client-hook-in-server-component
```

The workaround is to create a wrapper component with the following:
```
'use client';
export * from 'react-type-animation';
```
but it's less than ideal.

**Comment by sstackus** [comment]
I mean you have `useRef` in `src\hooks\useEffectOnce.tsx:4-7` and `src\hooks\useForwardRef.tsx:4`. My snippet is as I posted above - simply importing `react-type-animation` into an SSR app breaks it.

Which is fine I guess as this lib doesn't claim compatibility but SSR is a common technique and Next.js a common framework nowadays.

**Comment by sstackus** [comment]
I mean you have `useRef` in `src\hooks\useEffectOnce.tsx:4-7` and `src\hooks\useForwardRef.tsx:4`. My snippet is as I posted above - simply importing `react-type-animation` into an SSR app breaks it:

```
import {TypeAnimation} from '@/components/TypeAnimation';
//...
return <TypeAnimation sequence={['aa', 50]} />
```

> By using the preRenderFirstString prop, you can initially (pre-)render the very first string of your sequence. When used with SSR (Next.js or similar), the initial string will be included in the static HTML, which may benefit SEO.
> \- https://react-type-animation.netlify.app/examples#initially-pre-rendered

`preRenderFirstString` doesn't seem to help this case either.

**Comment by maxeth** [comment]
@sstackus 

Right, missed that one.

I have very little experience with Next 13 server components so I'm not sure if or what we can do here, but isn't that just a technical limitation of server components, in which case you simply gotta wrap it in a component with `"use client"` as you suggested already?

I mean it's impossible for this component to work without any client-side js, meaning it's supposed to be a client component, right?
