### ISSUE TITLE
How i know that the animation of typing ended ?

### ISSUE THREAD

**Issue by meddhiaka** [maxeth/react-type-animation#51]
for example when the text is rendering till the end, how i know that the text is rendered ?

**Comment by maxeth** [comment]
You can track the typing state via [callback functions](https://react-type-animation.netlify.app/examples#callback-functions)

If you repeat the animation X times, you can implement a counter via React state that gets incremented at the end of a sequence to know when the animation finishes its last repetition. See here: https://github.com/maxeth/react-type-animation/issues/23#issuecomment-1529579314
